const Unit = require('../models/Unit')

// Initialize units
let initUnits = () => {
    return new Promise((resolve, reject) => {

        Unit.insertMany([
            { "unit_name": "achates", "image": "achates.png" },
            { "unit_name": "adin", "image": "adin.png" },
            { "unit_name": "adlay", "image": "adlay.png" },
            { "unit_name": "ainos", "image": "ainos.png" },
            { "unit_name": "ains", "image": "ains.png" },
            { "unit_name": "aither", "image": "aither.png" },
            { "unit_name": "alencia", "image": "alencia.png" },
            { "unit_name": "alexa", "image": "alexa.png" },
            { "unit_name": "all rounder wanda", "image": "all_rounder_wanda.png" },
            { "unit_name": "ambitious tywin", "image": "ambitious_tywin.png" },
            { "unit_name": "angelica", "image": "angelica.png" },
            { "unit_name": "angelic montmorancy", "image": "angelic_montmorancy.png" },
            { "unit_name": "angel of light angelica", "image": "angel_of_light_angelica.png" },
            { "unit_name": "apocalypse ravi", "image": "apocalypse_ravi.png" },
            { "unit_name": "aramintha", "image": "aramintha.png" },
            { "unit_name": "arbiter vildred", "image": "arbiter_vildred.png" },
            { "unit_name": "archdemon shadow", "image": "archdemon_shadow.png" },
            { "unit_name": "aria", "image": "aria.jpg" },
            { "unit_name": "armin", "image": "armin.png" },
            { "unit_name": "arowell", "image": "arowell.png" },
            { "unit_name": "assassin cartuja", "image": "assassin_cartuja.png" },
            { "unit_name": "assassin cidd", "image": "assassin_cidd.png" },
            { "unit_name": "assassin coli", "image": "assassin_coli.png" },
            { "unit_name": "auxiliary lots", "image": "auxiliary_lots.png" },
            { "unit_name": "azalea", "image": "azalea.png" },
            { "unit_name": "baal and sezan", "image": "baal_and_sezan.png" },
            { "unit_name": "bad cat armin", "image": "bad_cat_armin.jpg" },
            { "unit_name": "baiken", "image": "baiken.png" },
            { "unit_name": "basar", "image": "basar.png" },
            { "unit_name": "bask", "image": "bask.png" },
            { "unit_name": "batisse", "image": "batisse.png" },
            { "unit_name": "belian", "image": "belian.png" },
            { "unit_name": "bellona", "image": "bellona.png" },
            { "unit_name": "benevolent romann", "image": "benevolent_romann.png" },
            { "unit_name": "blaze dingo", "image": "blaze_dingo.png" },
            { "unit_name": "blood blade karin", "image": "blood_blade_karin.png" },
            { "unit_name": "blood moon haste", "image": "blood_moon_haste.png" },
            { "unit_name": "briar witch iseria", "image": "briar_witch_iseria.png" },
            { "unit_name": "butcher corps inquisitor", "image": "butcher_corps_inquisitor.png" },
            { "unit_name": "camilla", "image": "camilla.png" },
            { "unit_name": "captain rikoris", "image": "captain_rikoris.png" },
            { "unit_name": "carmainerose", "image": "carmainerose.png" },
            { "unit_name": "carrot", "image": "carrot.png" },
            { "unit_name": "cartuja", "image": "cartuja.png" },
            { "unit_name": "cecilia", "image": "cecilia.png" },
            { "unit_name": "celeste", "image": "celeste.png" },
            { "unit_name": "celestial mercedes", "image": "celestial_mercedes.png" },
            { "unit_name": "celine", "image": "celine.png" },
            { "unit_name": "cerise", "image": "cerise.png" },
            { "unit_name": "cermia", "image": "cermia.png" },
            { "unit_name": "challenger dominiel", "image": "challenger_dominiel.png" },
            { "unit_name": "champion zerato", "image": "champion_zerato.png" },
            { "unit_name": "chaos inquisitor", "image": "chaos_inquisitor.png" },
            { "unit_name": "chaos sect axe", "image": "chaos_sect_axe.png" },
            { "unit_name": "charles", "image": "charles.png" },
            { "unit_name": "charlotte", "image": "charlotte.png" },
            { "unit_name": "chloe", "image": "chloe.png" },
            { "unit_name": "choux", "image": "choux.png" },
            { "unit_name": "christy", "image": "christy.png" },
            { "unit_name": "church of ilryos axe", "image": "church_of_ilryos_axe.png" },
            { "unit_name": "cidd", "image": "cidd.png" },
            { "unit_name": "clarissa", "image": "clarissa.png" },
            { "unit_name": "closer charles", "image": "closer_charles.png" },
            { "unit_name": "coli", "image": "coli.png" },
            { "unit_name": "commander lorina", "image": "commander_lorina.png" },
            { "unit_name": "command model laika", "image": "command_model_laika.png" },
            { "unit_name": "conquerer lilias", "image": "conquerer_lilias.png" },
            { "unit_name": "corvus", "image": "corvus.png" },
            { "unit_name": "crescent moon rin", "image": "crescent_moon_rin.png" },
            { "unit_name": "crimson armin", "image": "crimson_armin.png" },
            { "unit_name": "crozet", "image": "crozet.png" },
            { "unit_name": "dark corvus", "image": "dark_corvus.png" },
            { "unit_name": "desert jewel basar", "image": "desert_jewel_basar.png" },
            { "unit_name": "designer lilibet", "image": "designer_lilibet.png" },
            { "unit_name": "destina", "image": "destina.png" },
            { "unit_name": "diene", "image": "diene.png" },
            { "unit_name": "dingo", "image": "dingo.png" },
            { "unit_name": "dizzy", "image": "dizzy.png" },
            { "unit_name": "doll maker pearlhorizon", "image": "doll_maker_pearlhorizon.png" },
            { "unit_name": "dominiel", "image": "dominiel.png" },
            { "unit_name": "doris", "image": "doris.png" },
            { "unit_name": "eaton", "image": "eaton.png" },
            { "unit_name": "eda", "image": "eda.png" },
            { "unit_name": "elena", "image": "elena.png" },
            { "unit_name": "elphelt", "image": "elphelt.png" },
            { "unit_name": "elson", "image": "elson.png" },
            { "unit_name": "emilia", "image": "emilia.png" },
            { "unit_name": "enott", "image": "enott.png" },
            { "unit_name": "ervalen", "image": "ervalen.png" },
            { "unit_name": "fairytale tenebria", "image": "fairytale_tenebria.png" },
            { "unit_name": "faithless lidica", "image": "faithless_lidica.png" },
            { "unit_name": "falconer kluri", "image": "falconer_kluri.png" },
            { "unit_name": "fallen cecilia", "image": "fallen_cecilia.png" },
            { "unit_name": "fighter maya", "image": "fighter_maya.png" },
            { "unit_name": "flan", "image": "flan.png" },
            { "unit_name": "free spirit tieria", "image": "free_spirit_tieria.png" },
            { "unit_name": "furious", "image": "furious.png" },
            { "unit_name": "general purrgis", "image": "general_purrgis.png" },
            { "unit_name": "glenn", "image": "glenn.png" },
            { "unit_name": "gloomyrain", "image": "gloomyrain.png" },
            { "unit_name": "godmother", "image": "godmother.png" },
            { "unit_name": "great chief khawana", "image": "great_chief_khawana.png" },
            { "unit_name": "guider aither", "image": "guider_aither.png" },
            { "unit_name": "gunther", "image": "gunther.png" },
            { "unit_name": "hasol", "image": "hasol.jpg" },
            { "unit_name": "haste", "image": "haste.png" },
            { "unit_name": "hataan", "image": "hataan.png" },
            { "unit_name": "hazel", "image": "hazel.png" },
            { "unit_name": "helen", "image": "helen.png" },
            { "unit_name": "helga", "image": "helga.png" },
            { "unit_name": "holiday yufine", "image": "holiday_yufine.png" },
            { "unit_name": "hurado", "image": "hurado.png" },
            { "unit_name": "hwayoung", "image": "hwayoung.jpg" },
            { "unit_name": "ian", "image": "ian.png" },
            { "unit_name": "ilynav", "image": "ilynav.png" },
            { "unit_name": "inferno khawazu", "image": "inferno_khawazu.png" },
            { "unit_name": "iseria", "image": "iseria.png" },
            { "unit_name": "jack o", "image": "jack_o.jpg" },
            { "unit_name": "januta", "image": "januta.jpg" },
            { "unit_name": "jecht", "image": "jecht.png" },
            { "unit_name": "jena", "image": "jena.png" },
            { "unit_name": "judge kise", "image": "judge_kise.png" },
            { "unit_name": "judith", "image": "judith.png" },
            { "unit_name": "kanna", "image": "kanna.png" },
            { "unit_name": "karin", "image": "karin.png" },
            { "unit_name": "kawerik", "image": "kawerik.png" },
            { "unit_name": "kayron", "image": "kayron.png" },
            { "unit_name": "ken", "image": "ken.png" },
            { "unit_name": "khawana", "image": "khawana.png" },
            { "unit_name": "khawazu", "image": "khawazu.png" },
            { "unit_name": "kikirat v2", "image": "kikirat_v2.png" },
            { "unit_name": "kiris", "image": "kiris.png" },
            { "unit_name": "kise", "image": "kise.png" },
            { "unit_name": "kitty clarissa", "image": "kitty_clarissa.png" },
            { "unit_name": "kizuna ai", "image": "kizuna_ai.jpg" },
            { "unit_name": "kluri", "image": "kluri.png" },
            { "unit_name": "krau", "image": "krau.png" },
            { "unit_name": "landy", "image": "landy.png" },
            { "unit_name": "last rider krau", "image": "last_rider_krau.jpg" },
            { "unit_name": "lena", "image": "lena.png" },
            { "unit_name": "leo", "image": "leo.png" },
            { "unit_name": "lidica", "image": "lidica.png" },
            { "unit_name": "lilias", "image": "lilias.png" },
            { "unit_name": "lilibet", "image": "lilibet.png" },
            { "unit_name": "lionheart cermia", "image": "lionheart_cermia.jpg" },
            { "unit_name": "little queen charlotte", "image": "little_queen_charlotte.png" },
            { "unit_name": "lorina", "image": "lorina.png" },
            { "unit_name": "lots", "image": "lots.png" },
            { "unit_name": "lucy", "image": "lucy.png" },
            { "unit_name": "ludwig", "image": "ludwig.png" },
            { "unit_name": "luluca", "image": "luluca.png" },
            { "unit_name": "luna", "image": "luna.png" },
            { "unit_name": "magic scholar doris", "image": "magic_scholar_doris.png" },
            { "unit_name": "maid chloe", "image": "maid_chloe.png" },
            { "unit_name": "martial artist ken", "image": "martial_artist_ken.png" },
            { "unit_name": "mascot hazel", "image": "mascot_hazel.png" },
            { "unit_name": "maya", "image": "maya.png" },
            { "unit_name": "mediator kawerik", "image": "mediator_kawerik.png" },
            { "unit_name": "melany", "image": "melany.png" },
            { "unit_name": "melissa", "image": "melissa.png" },
            { "unit_name": "mercedes", "image": "mercedes.png" },
            { "unit_name": "mercenary helga", "image": "mercenary_helga.png" },
            { "unit_name": "milim", "image": "milim.png" },
            { "unit_name": "mirsa", "image": "mirsa.png" },
            { "unit_name": "mistychain", "image": "mistychain.png" },
            { "unit_name": "montmorancy", "image": "montmorancy.png" },
            { "unit_name": "mort", "image": "mort.png" },
            { "unit_name": "mucacha", "image": "mucacha.png" },
            { "unit_name": "mui", "image": "mui.png" },
            { "unit_name": "muse rima", "image": "muse_rima.png" },
            { "unit_name": "muwi", "image": "muwi.jpg" },
            { "unit_name": "nemunas", "image": "nemunas.png" },
            { "unit_name": "operator sigret", "image": "operator_sigret.png" },
            { "unit_name": "orte", "image": "orte.jpg" },
            { "unit_name": "otillie", "image": "otillie.png" },
            { "unit_name": "pavel", "image": "pavel.png" },
            { "unit_name": "pearlhorizon", "image": "pearlhorizon.png" },
            { "unit_name": "peira", "image": "peira.jpg" },
            { "unit_name": "penelope", "image": "penelope.png" },
            { "unit_name": "pirate captain flan", "image": "pirate_captain_flan.jpg" },
            { "unit_name": "politis", "image": "politis.png" },
            { "unit_name": "purrgis", "image": "purrgis.png" },
            { "unit_name": "pyllis", "image": "pyllis.png" },
            { "unit_name": "ram", "image": "ram.png" },
            { "unit_name": "ran", "image": "ran.png" },
            { "unit_name": "ras", "image": "ras.png" },
            { "unit_name": "ravi", "image": "ravi.png" },
            { "unit_name": "ray", "image": "ray.png" },
            { "unit_name": "rem", "image": "rem.png" },
            { "unit_name": "remnant violet", "image": "remnant_violet.jpg" },
            { "unit_name": "requiemroar", "image": "requiemroar.png" },
            { "unit_name": "researcher carrot", "image": "researcher_carrot.png" },
            { "unit_name": "righteous thief roozid", "image": "righteous_thief_roozid.png" },
            { "unit_name": "rikoris", "image": "rikoris.png" },
            { "unit_name": "rima", "image": "rima.png" },
            { "unit_name": "rimuru", "image": "rimuru.png" },
            { "unit_name": "rin", "image": "rin.png" },
            { "unit_name": "roaming warrior leo", "image": "roaming_warrior_leo.png" },
            { "unit_name": "roana", "image": "roana.png" },
            { "unit_name": "romann", "image": "romann.png" },
            { "unit_name": "roozid", "image": "roozid.png" },
            { "unit_name": "rose", "image": "rose.png" },
            { "unit_name": "ruele of light", "image": "ruele_of_light.png" },
            { "unit_name": "sage baal and sezan", "image": "sage_baal_and_sezan.png" },
            { "unit_name": "schuri", "image": "schuri.png" },
            { "unit_name": "seaside bellona", "image": "seaside_bellona.png" },
            { "unit_name": "senya", "image": "senya.png" },
            { "unit_name": "serila", "image": "serila.png" },
            { "unit_name": "sez", "image": "sez.png" },
            { "unit_name": "shadow knight pyllis", "image": "shadow_knight_pyllis.png" },
            { "unit_name": "shadow rose", "image": "shadow_rose.png" },
            { "unit_name": "shooting star achates", "image": "shooting_star_achates.png" },
            { "unit_name": "shuna", "image": "shuna.png" },
            { "unit_name": "sigret", "image": "sigret.png" },
            { "unit_name": "silk", "image": "silk.png" },
            { "unit_name": "silver blade aramintha", "image": "silver_blade_aramintha.png" },
            { "unit_name": "sinful angelica", "image": "sinful_angelica.png" },
            { "unit_name": "sol", "image": "sol.png" },
            { "unit_name": "solitaria", "image": "solitaria.png" },
            { "unit_name": "sonia", "image": "sonia.png" },
            { "unit_name": "specimen sez", "image": "specimen_sez.png" },
            { "unit_name": "specter tenebria", "image": "specter_tenebria.png" },
            { "unit_name": "spirit eye celine", "image": "spirit_eye_celine.png" },
            { "unit_name": "straze", "image": "straze.png" },
            { "unit_name": "summertime iseria", "image": "summertime_iseria.png" },
            { "unit_name": "support model brinus", "image": "support_model_brinus.png" },
            { "unit_name": "surin", "image": "surin.png" },
            { "unit_name": "sven", "image": "sven.png" },
            { "unit_name": "tamarinne", "image": "tamarinne.png" },
            { "unit_name": "taranor guard", "image": "taranor_guard.png" },
            { "unit_name": "taranor royal guard", "image": "taranor_royal_guard.png" },
            { "unit_name": "tempest surin", "image": "tempest_surin.png" },
            { "unit_name": "tenebria", "image": "tenebria.png" },
            { "unit_name": "tieria", "image": "tieria.png" },
            { "unit_name": "top model luluca", "image": "top_model_luluca.jpg" },
            { "unit_name": "troublemaker crozet", "image": "troublemaker_crozet.png" },
            { "unit_name": "tywin", "image": "tywin.png" },
            { "unit_name": "verdant adin", "image": "verdant_adin.jpg" },
            { "unit_name": "vigilante leader glenn", "image": "vigilante_leader_glenn.jpg" },
            { "unit_name": "vildred", "image": "vildred.png" },
            { "unit_name": "violet", "image": "violet.png" },
            { "unit_name": "vivian", "image": "vivian.png" },
            { "unit_name": "wanda", "image": "wanda.png" },
            { "unit_name": "wanderer silk", "image": "wanderer_silk.png" },
            { "unit_name": "watcher schuri", "image": "watcher_schuri.png" },
            { "unit_name": "yoonryoung", "image": "yoonryoung.jpg" },
            { "unit_name": "yufine", "image": "yufine.png" },
            { "unit_name": "yuna", "image": "yuna.png" },
            { "unit_name": "zahhak", "image": "zahhak.png" },
            { "unit_name": "zealot carmainerose", "image": "zealot_carmainerose.png" },
            { "unit_name": "zeno", "image": "zeno.png" },
            { "unit_name": "zerato", "image": "zerato.png" }]).then((docs) => {
                resolve(docs)
            }).catch((err) => {
                reject(err)
            })
    })
}

// Get all units
let getAllUnits = () => {
    return new Promise((resolve, reject) => {
        Unit.find({}).then((result) => {
            resolve(result)
        }).catch((err) => {
            reject(err)
        })
    })
}

// Get units details by id
let getUnitsById = (ids) => {
    return new Promise((resolve, reject) => {
        Unit.find({
            _id: {
                $in: ids
            }
        }).then((result) => {
            resolve(result)
        }).catch((err) => {
            reject(err)
        })
    })
}

// Get unit details by id
let getUnitById = (unit_id) => {
    return new Promise((resolve, reject) => {
        Unit.find({
            _id: unit_id
        }).then((result) => {
            resolve(result)
        }).catch((err) => {
            reject(err)
        })
    })
}

module.exports = {
    initUnits,
    getAllUnits,
    getUnitsById,
    getUnitById
}